# Always re-run the benchmark.
transRate:  transRate.cc  utils.hh
	g++ -std=gnu11 -O0 -static -o transRate transRate.cc 

getThreshold:  getThreshold.cc utils.hh 
	g++ -std=gnu11 -O0 -static -o getThreshold getThreshold.cc

SpectrePrefetch:  SpectrePrefetch.cc  utils.hh 
	g++ -std=gnu11 -O0 -static -o SpectrePrefetch SpectrePrefetch.cc